import { FeatherModule } from 'angular-feather';
import {
    Camera, Clock, Calendar, Trash2, Plus, ArrowLeft, ArrowRight, Heart, Github, Users, Activity, FileText, Search, Settings, Pocket, Bell, Trash, Eye, Mail, DollarSign, ChevronRight, ChevronLeft, ChevronDown, FilePlus, Edit2, Edit, X, Check, UploadCloud, MoreVertical, MoreHorizontal, CreditCard, Download,
    Tool, Airplay, Briefcase, Facebook, Linkedin, Twitter, Repeat, Upload, Grid, RefreshCcw, Phone, File, AlertCircle, Edit3, Copy, Send, ZapOff, Zap, Target, SkipBack, Shuffle,
    Save, Sliders, Trello, Twitch, Slash, CheckSquare, Cast, MapPin, Home, LogIn, Book, VolumeX, Percent, Link, PlusCircle, Loader, Share, ChevronUp, Link2, Paperclip
} from 'angular-feather/icons';
export const icons = {
    Camera,
    Calendar,
    Heart,
    Github,
    Users,
    Activity,
    FileText,
    Search,
    Settings,
    Bell,
    ArrowLeft,
    ArrowRight,
    Check,
    Trash2,
    Trash,
    Plus,
    Eye,
    Mail,
    DollarSign,
    ChevronRight,
    ChevronLeft,
    ChevronDown,
    Pocket,
    FilePlus,
    Edit2,
    UploadCloud,
    X,
    MoreHorizontal,
    MoreVertical,
    CreditCard,
    Download,
    Tool,
    Airplay,
    Briefcase,
    Facebook,
    Linkedin,
    Twitter,
    Repeat,
    Upload,
    Grid,
    RefreshCcw,
    Phone,
    File,
    AlertCircle,
    Edit3,
    Copy,
    Send,
    Save,
    ZapOff,
    Zap,
    Target,
    SkipBack,
    Shuffle,
    Sliders,
    Trello,
    Twitch,
    Slash,
    CheckSquare,
    Cast,
    MapPin,
    Home,
    Clock,
    Edit,
    LogIn,
    Book,
    VolumeX,
    Percent,
    Link,
    PlusCircle,
    Loader,
    Share,
    ChevronUp,
    Paperclip,
    Link2
};
export const IconsModule = [
    FeatherModule
];